module.exports = Object.freeze({
    CHKAllFIELD: 'الرجاء مراجعة جميع الحقول.',
    WELCOME_EMAIL: 'Welcome in KeyMarket!!! Your account please using KeyMarket account for buying and selling anything in the worlds.',
    VERIFICATION_MSG: " authentication code to verify your KeyMarket account. Valid for one hour. Please do not share this authentication code to anyone for security reasons.",
    VERIFICATION_MAIL: "Hey, Thanks for signing up! Your account has been created. Please verify your account by using this authentication code ",
    DEACTIVE_ACCOUNT: 'حسابك غير نشط الرجاء الاتصال بالدعم الفني لتشغيل حسابك',
    SESSION_CLOSED: 'تم إغلاق الجلسة الآن ، يرجى تسجيل الدخول أولاً',
    MSGSENDSUCCESS: 'تم ارسال الرساله بنجاح.',
    MSGSUCCESS: "تمت الاضافه بنجاح",
    MSGDELETE: "تم الحذف",
    MSGERR: "خطاء في الادخال",
    MSGSUCCESSUPDATE: "تم التعديل بنجاح",
    MSGCONTACTSENDSUCCESS: "تم ارسال البطاقه .",
    ERR: "الرجاء المحاوله لاحقا",
    ALREADYADDED: " اسم المستخدم موجود مسبقا الرجاء المحاوله مره اخري",
    NODATAFOUND: "لا توجد بيانات",
    CHECK_YOUR_EMAIL: "صيغة البريد الالكتروني غير صحيحه",
    PASSWORD_LENGTH: "يجب ان تتكون كلمة المرور من 8-20 حرف",
    USER_NOT_FOUND: "المستخدم غير موجود",
    PASS_NT_MTCH: "كلمة المرور غير صحيحه",
    LOGINSUCCESSFULL: "تم تسجيل الدخول بنجاح",
    DEACTIVATEUSER: "اسم المستخدم غير مفعل الرجاء الاتصال بنا",
    VERIFYMOBILE: "الرجاء التاكد من رقم الهاتف",
    USERALREADY: "المستخدم موجود مسبقا",
    EMAIL_VALIDATION: "Email Id already available. Please check user different email address.",
    USERNAME_VALIDATION: "اسم المستخدم موجود مسبقا الرجاء المحاوله باسم مستخدم اخر",
    USER_REGISTER: "تم التسجيل بنجاح , الرجاء التاكد من رقم الهاتف",
    ALL_CAT: "البحث في جميع الاقسام",
    NO_DATA: "لاتوجد بيانات",
    SUCCESSFULLY_DELETED: "تم الحذف",
    PWD_SUB: "هل نسيت كلمت المرور؟",
    PWD_CNG: "تم تغيير كلمة المرور الرجاء مراجعة البريد الالكتروني لاكمال العمليه",
    NOTAVAILABLE: "المستخدم غير متاح",
    NOT_ACTIVE: "المستخدم غير مفعل",
    USER_NOT_FOUND: "لم يتم العثور علي المستخدم",
    ALL_SUB_CAT: "الحصول على جميع الاقسام الفرعية",
    CHAT_HST: "الحصول على سجل الدردشة",
    NO_CHAT: "لا يوجد سجل دردشة",
    NO_CALL: "لا سجل المكالمات.",
    FREE: "مجانا",
    MONTHLY: "شهري.",
    QUARTERLY: "ربع سنه",
    HALFYEARLY: "نصف سنه",
    YEARLY: "سنوي.",
    ALL_PACKAGES: "الحصول علي الباقه كامله",
    NO_PRODUCT_FOUND: "لم يتم العثور على المنتج",
    PRO_EDIT: "تم التعديل بنجاح",
    USER_ALRD_RGST: "رقم الهاتف موجود مسبقا الرجاء المحاوله برقم اخر",
    OTP_SEND_SUCCESS: "تم ارسال رمز الOTP",
    USR_VERIFY: "تم التحقق من المستخدم",
    SHRD_SUCESS: "تمت مشاركة الفديو بنجاح",
    REG_SUB: "التسجيل",
    SEND_OTP: "KeyMarket OTP",
    ADMIN_EMAIL: "samyotechindore@gmail.com",
    INTERNAL_ERROR: "حدثت مشكله في الشبكه الرجاء المحاوله لاحقا",
    MY_FOLLOWER: "الحصول علي متابعين اكثر",
    UNFOLLOW_SUCCESS: "تم الغاء المتابعه",
    FOLLOW_SUCCESS: "تمت المتابعه",
    ALREADYFOLLOW: "تمت المتابعه مسبقا",
    STRATEDVIDEOCHAT: "البداء في محادثة فديو",
    ENDEDVIDEOCHAT: "انهاء محادثة فديو",
    MY_CONVERSION: "الحصول على محادثتي.",
    MSGUPDATEDPASSWORD: "كلمة المرور هي:",
    EMAILIDNOTFOUND: "البريد الالكتروني غير موجود",
    MSGCHANGEPASSWORD: "تم تغيير كلمة المرور",
    CURRENT_VERSION: "النسخه الحاليه",
    COMPLAINT_ADDED: "تم رفع الشكوي",
    PROFILE_UPDATED: "تم تعديل الملف الشخصي",
    CONTACT_SEND_SUCCESS: "تم ارسال الاسم",
    PRODUCT_DETAILS: " تم حذف المنتج",
    VIEWADDEDSUCCESS: "تم اضافة المشاهده",
    FORWORDS: "تحويل",
    MSGUNBLOCK: "الان يمكنك اجراء المحادثات والاتصال",
    MSGBLOCK: "لن تتمكن بعد الآن من الاتصال بك أو إرسال رسائل إليك.",
    BLOCKLIST: " قائمة الحظر",
    COMMENTS: "التعليقات",
    COMMENT_DELETED: "تم حذف التعليق ",
    USER_DELETED: "تم حذف المستخدم",
    DISLIKED: "الغاء اعجاب",
    PRODUCT_DEACTIVATED_SUCCESS: "تم إلغاء عرض المنتج بنجاح.",
    PRODUCT_ACCESS_SUCCESS: "تم تحديث حالة  المنتج بنجاح.",
    PRODUCT_SOLD_SUCCESS: "تم تحديث حالة البيع  بنجاح",
    VIDEO_REPORTED_SUCCESS: "تم الإبلاغ عن الفيديو بنجاح",
    PRODUCTS: "المنتجات",
    MSGCOMMENTD_ON_PRODUCT: "التعليق علي الفديو الخاص  بك",
    NOTIFICATIONS: "الاشعارات",
    PRODUCTS: "المنتجات",
    PLEASE_UNBLOCK: "الغاء الحظر ",
    UNBLOCK_MESG: "قبل ارسال رساله او اجراء اتصال",
    BLOCK_MSG: " قام بحظرك. لا يمكنك إرسال رسالة أو إجراء مكالمة.",
    MSGSENDSUCCESS: "تم ارسال الرساله",
    PURCHASEREQUEST: "طلب الشراء",
    USERNAMEALREDYEXIST: "اسم المستخدم موجود مسبقا",
    // get all package message start
    ALLP: "كل الحزمة.",
    PNOTF: "الحزمة غير موجودة",
    //Checkmypackage MESSAGE START
    UNOTF: "المستخدم ليس موجود.",
    SWRON: "هل هناك خطب ما.",
    UPHE: "انتهت صلاحية حزمة المستخدم.",
    UPIA: "حزمة المستخدم نشطة.",
    USHNF: "لم يتم العثور على سجل اشتراك المستخدم.",
    //subscrib user message start 
    USS: "اشتراك المستخدم بنجاح.",
    INPUTWRONG: 'إدخال المستخدم المطلوب',
    //get my subsription histry message start
    ALLSUBSHTRY: "كل تاريخ الاشتراك.",
    SUBSHNOTF: "لم يتم العثور على سجل الاشتراك.",
    SOMEWRONG: "هل هناك خطب ما.",
    //DISCOVER DATA MESSAGE START
    UREQALLFILD: "يتطلب المستخدم جميع الحقول",
    MSGLIKE_ON_PRODUCT: "اعجبك الفيديو",
    SINCH_OTP_SEND: "لقد أرسلنا OTP على رقم هاتفك المحمول",
    SINCH_OTP_SEND_ERR: "يبدو أن مزود الرسائل القصيرة لا يعمل. يرجى المحاولة بعد مرور بعض الوقت.",
    SINCH_OTP_VERIFY_ERR: "هوية أو رمز غير صالح",
    PROFILE_USER_PRODUCT: "المنتج وفقا للمستخدم",
    PROFILE_NO_USER_PRODUCT: "ملف تعريف المستخدم خاص",
    PRODUCT_REPUBLISHED_SUCCESS: "تم إعادة نشر المنتج بنجاح",
});