module.exports = Object.freeze({
    CAR_ID: 'd7887cc9964a5a7a',
    FOOD_ID: 'd7887cc9964a5a7a',
    CHKAllFIELD: 'please check all the fields.',
    WELCOME_EMAIL: 'Welcome in KeyMarket!!! You can use KeyMarket account for buying and selling anything in the worlds.',
    VERIFICATION_MSG: " authentication code to verify your KeyMarket account. Valid for one hour. Please do not share this authentication code to anyone for security reasons.",
    VERIFICATION_MAIL: "Hey,<br><br> Thanks for signing up with KeyMarket!!! Your account has been created. Please verify your account by using this authentication code ",
    EMAIL_SIGNATURE: "<br><br> Thanks<br> KeyMarket Team",
    DEACTIVE_ACCOUNT: 'User has deactivated your account, please contact to admin to resume your login access.',
    SESSION_CLOSED: 'Session is closed now please login first',
    MSGSENDSUCCESS: 'message send Successfully.',
    MSGSUCCESS: "Added Successfully",
    MSGDELETE: "Deleted Successfully",
    MSGERR: "Error in insert",
    MSGSUCCESSUPDATE: "Updated Successfully",
    MSGCONTACTSENDSUCCESS: "Contact send Successfully.",
    ERR: "Please try after some time.",
    ALREADYADDED: "Already Added",
    NODATAFOUND: "No data found",
    CHECK_YOUR_EMAIL: "Invalid email Format",
    PASSWORD_LENGTH: "Password must be 8-20 characters long",
    USER_NOT_FOUND: "User not found",
    PASS_NT_MTCH: "Password does not match. Please use correct password.",
    LOGINSUCCESSFULL: "User login successfully",
    DEACTIVATEUSER: "You are not active user. Please contact to admin.",
    VERIFYMOBILE: "Please verify your Mobile no.",
    USERALREADY: "User already registered",
    USERNAME_VALIDATION: "Username already available. Please check with another combination.",
    EMAIL_VALIDATION: "Email Id already available. Please check user different email address.",
    USER_REGISTER: "User has been registered successfully. Please verify your Account.",
    ALL_CAT: "Get all Categories",
    NO_DATA: "No data found.",
    SUCCESSFULLY_DELETED: "successfully Deleted",
    PWD_SUB: "Forget Password",
    PWD_CNG: "Password updated successfully. Please check your email id for updated Password.",
    NOTAVAILABLE: "User not available.",
    NOT_ACTIVE: "User not active.",
    USER_NOT_FOUND: "User not found.",
    ALL_SUB_CAT: "Get all Sub-Categories.",
    CHAT_HST: "Get chat history.",
    NO_CHAT: "No Chat history.",
    NO_CALL: "No Call history.",
    FREE: "Free.",
    MONTHLY: "Monthly.",
    QUARTERLY: "Quarterly.",
    HALFYEARLY: "Half Yearly.",
    YEARLY: "Yearly.",
    ALL_PACKAGES: "Get all Packages.",
    NO_PRODUCT_FOUND: "No product found.",
    PRO_EDIT: "Product Edit successfully",
    USER_ALRD_RGST: "Mobile no. already registered. Please use different no.",
    OTP_SEND_SUCCESS: "OTP send successfully.",
    USR_VERIFY: "User verify successfully",
    SHRD_SUCESS: "Snap shared successfully.",
    REG_SUB: "Registration",
    SEND_OTP: "KeyMarket OTP",
    ADMIN_EMAIL: "samyotechindore@gmail.com",
    INTERNAL_ERROR: "Internal server error.",
    MY_FOLLOWER: "Get my followers.",
    UNFOLLOW_SUCCESS: "Unfollow Successfully.",
    FOLLOW_SUCCESS: "Follow Successfully.",
    ALREADYFOLLOW: "You already follow this user.",
    STRATEDVIDEOCHAT: "Started a video chat",
    ENDEDVIDEOCHAT: "Video chat ended",
    MY_CONVERSION: "Get my conversation.",
    MSGUPDATEDPASSWORD: "Your updated password is",
    EMAILIDNOTFOUND: "Email id not found",
    MSGCHANGEPASSWORD: "Your updated password Changed.",
    CURRENT_VERSION: "Current Version",
    COMPLAINT_ADDED: "Complaint added Successfully.",
    PROFILE_UPDATED: "Profile has been updated successfully",
    CONTACT_SEND_SUCCESS: "Contact send successfully.",
    PRODUCT_DETAILS: "Product Details",
    VIEWADDEDSUCCESS: "View added successfully",
    FORWORDS: "Forewords",
    MSGUNBLOCK: "Now you can make call and send message to ",
    MSGBLOCK: "will no longer be able to call you or send you messages.",
    BLOCKLIST: "Block list",
    COMMENTS: "Comment",
    COMMENT_DELETED: "comment deleted successfully.",
    USER_DELETED: "User deleted successfully.",
    DISLIKED: "Disliked",
    PRODUCT_DEACTIVATED_SUCCESS: "Product deactivated successfully.",
    PRODUCT_ACCESS_SUCCESS: "Product access status updated successfully.",
    PRODUCT_SOLD_SUCCESS: "Product sold status updated successfully.",
    VIDEO_REPORTED_SUCCESS: "video reported successfully.",
    PRODUCTS: "Products",
    MSGCOMMENTD_ON_PRODUCT: "commented on your video",
    NOTIFICATIONS: "Notifications",
    PRODUCTS: "Products",
    PLEASE_UNBLOCK: "Please unblock ",
    UNBLOCK_MESG: " before sending message or make call.",
    BLOCK_MSG: " has blocked you. You can not send message or make call.",
    MSGSENDSUCCESS: "message send Successfully.",
    PURCHASEREQUEST: "Purchase request",
    USERNAMEALREDYEXIST: "username already exists",
    // get all package message start
    ALLP: "All package.",
    PNOTF: "Package Not Found",
    //Checkmypackage MESSAGE START
    UNOTF: "User Not Found.",
    SWRON: "something wrong.",
    UPHE: "User Package has expired.",
    UPIA: "User Package is Active.",
    USHNF: "User subscription History Not Found.",
    //subscrib user message start 
    USS: "user subscribe successfull.",
    INPUTWRONG: 'Required User Input ',
    //get my subsription histry message start
    ALLSUBSHTRY: "All Subscription History.",
    SUBSHNOTF: "Subscription History Not Found.",
    SOMEWRONG: "Something Wrong.",
    //DISCOVER DATA MESSAGE START
    UREQALLFILD: "User Require All Fields",
    MSGLIKE_ON_PRODUCT: "liked your video",
    SINCH_OTP_SEND: "We have sent OTP on your mobile number.",
    SINCH_OTP_SEND_ERR: "It seems that sms provider not working. Please try after some time.",
    SINCH_OTP_VERIFY_ERR: "Invalid identity or code.",
    PROFILE_USER_PRODUCT: "Product according to user",
    PROFILE_NO_USER_PRODUCT: "User profile is private",
    PRODUCT_REPUBLISHED_SUCCESS: "Product re-published successfully",
});